CREATE TABLE USER_INFO (
	USER_ID VARCHAR(20) NOT NULL,
	USER_NAME VARCHAR(20) NOT NULL,
	USER_AGE INTEGER NOT NULL,
	USER_JOIN_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(USER_ID)
);

CREATE TABLE ACCOUNT_INFO (
	USER_ID VARCHAR(20) NOT NULL,
	ACCOUNT_NUM VARCHAR(7) NOT NULL,
	PRIMARY KEY(ACCOUNT_NUM)
);

CREATE TABLE ACCOUNT_HISTORY (
	ACCOUNT_NUM VARCHAR(7) NOT NULL,
	WITHDRAWL_YN CHAR(1) NOT NULL,
	WITHDRAWL_AMOUNT BIGINT NOT NULL,
	WITHDRAWL_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);